#!/bin/bash -ex
install()
{
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

sid()
{
    DEBIAN_FRONTEND=noninteractive apt-get -f -y -t sid \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.27.1/install.sh | bash
source ~/.profile || true
nvm install 4.0

apt-get update
install git
install screen
install rdiff-backup
install git
install mysql-server
install openjdk-7-jre
install supervisor
install build-essential

#echo "deb http://http.us.debian.org/debian sid main" >> /etc/apt/sources.list.d/sources.list
#sid python2.7
