#!/bin/bash -e

cd /usr/games/minecraft
./generate-sslcert.sh

#git init
#git remote add origin https://github.com/hexparrot/mineos-node
git config core.filemode false

mkdir -p /var/games/minecraft/

ln -s /usr/games/minecraft/mineos_console.js /usr/local/bin/mineos
